import type { PlayerDefinition } from "@/types/player";

export const STARTER_PLAYERS: PlayerDefinition[] = [
  // --- GOALKEEPER ---
  {
    id: "aegis",
    name: "Aegis",
    archetype: "keeper",
    roleTags: ["goalkeeper"],
    tier: "silver",
    stats: {
      pace: 35,
      shooting: 15,
      passing: 50,
      defense: 60,
      physical: 65,
      goalkeeping: 88,
    },
    passive: {
      id: "aegis-passive",
      name: "Iron Wall",
      description: "Saves are 15% more effective when the team is defending.",
      trigger: "on_defense",
      effect: { type: "stat_boost", stat: "goalkeeping", magnitude: 15, durationTicks: 0 },
    },
    activeSkill: {
      id: "aegis-active",
      name: "Command Area",
      description: "Boosts nearby defenders' positioning for a short time.",
      cooldownTicks: 30,
      target: "team",
      effect: { type: "stat_boost", stat: "defense", magnitude: 10, durationTicks: 10 },
    },
    ultimate: {
      id: "aegis-ult",
      name: "Fortress",
      description: "Becomes nearly unbeatable for a brief window. All shots face maximum resistance.",
      chargeRequired: 60,
      effect: { type: "stat_boost", stat: "goalkeeping", magnitude: 40, durationTicks: 8 },
    },
    portrait: "aegis",
    flavorText: "The last line. The final word. Nothing gets past Aegis.",
  },

  // --- ATTACKER 1 ---
  {
    id: "blaze",
    name: "Blaze",
    archetype: "striker",
    roleTags: ["attacker"],
    tier: "silver",
    stats: {
      pace: 90,
      shooting: 85,
      passing: 45,
      defense: 20,
      physical: 55,
      goalkeeping: 5,
    },
    passive: {
      id: "blaze-passive",
      name: "Ignition",
      description: "Shooting increases by 10% after each successful dribble in a possession.",
      trigger: "on_possession",
      effect: { type: "stat_boost", stat: "shooting", magnitude: 10, durationTicks: 0 },
    },
    activeSkill: {
      id: "blaze-active",
      name: "Burst Sprint",
      description: "Doubles pace for a short dash, breaking past defenders.",
      cooldownTicks: 25,
      target: "self",
      effect: { type: "stat_boost", stat: "pace", magnitude: 100, durationTicks: 5 },
    },
    ultimate: {
      id: "blaze-ult",
      name: "Inferno Strike",
      description: "Unleashes a devastating shot with massively boosted power and accuracy.",
      chargeRequired: 50,
      effect: { type: "stat_boost", stat: "shooting", magnitude: 60, durationTicks: 3 },
    },
    portrait: "blaze",
    flavorText: "Fast as fire. Twice as dangerous. Blaze doesn't miss.",
  },

  // --- ATTACKER 2 ---
  {
    id: "phantom",
    name: "Phantom",
    archetype: "striker",
    roleTags: ["attacker"],
    tier: "silver",
    stats: {
      pace: 80,
      shooting: 75,
      passing: 65,
      defense: 25,
      physical: 40,
      goalkeeping: 5,
    },
    passive: {
      id: "phantom-passive",
      name: "Ghost Movement",
      description: "Has a chance to evade tackles automatically.",
      trigger: "always",
      effect: { type: "special", magnitude: 20, durationTicks: 0 },
    },
    activeSkill: {
      id: "phantom-active",
      name: "Shadow Step",
      description: "Teleports past the nearest defender, creating a clear path.",
      cooldownTicks: 30,
      target: "self",
      effect: { type: "disrupt", magnitude: 30, durationTicks: 3 },
    },
    ultimate: {
      id: "phantom-ult",
      name: "Vanishing Act",
      description: "Becomes untouchable for a moment and delivers a precision strike.",
      chargeRequired: 55,
      effect: { type: "stat_boost", stat: "shooting", magnitude: 50, durationTicks: 4 },
    },
    portrait: "phantom",
    flavorText: "Now you see him. Now you don't. But the goal is already in.",
  },

  // --- MIDFIELDER ---
  {
    id: "volt",
    name: "Volt",
    archetype: "playmaker",
    roleTags: ["midfielder"],
    tier: "silver",
    stats: {
      pace: 70,
      shooting: 55,
      passing: 90,
      defense: 45,
      physical: 50,
      goalkeeping: 5,
    },
    passive: {
      id: "volt-passive",
      name: "Circuit",
      description: "Successful passes boost the next teammate's action by 8%.",
      trigger: "on_possession",
      effect: { type: "stat_boost", magnitude: 8, durationTicks: 0 },
    },
    activeSkill: {
      id: "volt-active",
      name: "Spark Pass",
      description: "Delivers a perfect through ball that boosts the receiver's next action.",
      cooldownTicks: 20,
      target: "ally",
      effect: { type: "stat_boost", stat: "shooting", magnitude: 20, durationTicks: 5 },
    },
    ultimate: {
      id: "volt-ult",
      name: "Overcharge",
      description: "Electrifies the entire team, boosting all stats temporarily.",
      chargeRequired: 65,
      effect: { type: "stat_boost", magnitude: 15, durationTicks: 12 },
    },
    portrait: "volt",
    flavorText: "Every touch is a spark. Every pass is a bolt. Volt controls the current.",
  },

  // --- DEFENDER ---
  {
    id: "titan",
    name: "Titan",
    archetype: "enforcer",
    roleTags: ["defender"],
    tier: "silver",
    stats: {
      pace: 45,
      shooting: 25,
      passing: 40,
      defense: 90,
      physical: 88,
      goalkeeping: 5,
    },
    passive: {
      id: "titan-passive",
      name: "Immovable",
      description: "Cannot be dribbled past when stamina is above 50%.",
      trigger: "on_defense",
      effect: { type: "stat_boost", stat: "defense", magnitude: 20, durationTicks: 0 },
    },
    activeSkill: {
      id: "titan-active",
      name: "Crushing Tackle",
      description: "Guaranteed ball recovery, disrupts the attacker's next action.",
      cooldownTicks: 25,
      target: "enemy",
      effect: { type: "disrupt", magnitude: 40, durationTicks: 5 },
    },
    ultimate: {
      id: "titan-ult",
      name: "Earthquake",
      description: "Shakes the field, disrupting all enemy players and recovering possession.",
      chargeRequired: 60,
      effect: { type: "disrupt", magnitude: 50, durationTicks: 8 },
    },
    portrait: "titan",
    flavorText: "Mountains move. Titan doesn't.",
  },

  // --- HYBRID / SPECIALIST ---
  {
    id: "hawk",
    name: "Hawk",
    archetype: "specialist",
    roleTags: ["hybrid"],
    tier: "silver",
    stats: {
      pace: 75,
      shooting: 60,
      passing: 70,
      defense: 65,
      physical: 60,
      goalkeeping: 5,
    },
    passive: {
      id: "hawk-passive",
      name: "Bird's Eye",
      description: "Intercepts passes 15% more often. Reads the game before anyone else.",
      trigger: "always",
      effect: { type: "stat_boost", stat: "defense", magnitude: 15, durationTicks: 0 },
    },
    activeSkill: {
      id: "hawk-active",
      name: "Precision Cross",
      description: "Delivers a pinpoint cross that massively boosts the target's heading chance.",
      cooldownTicks: 22,
      target: "ally",
      effect: { type: "stat_boost", stat: "shooting", magnitude: 25, durationTicks: 4 },
    },
    ultimate: {
      id: "hawk-ult",
      name: "Aerial Supremacy",
      description: "Dominates the air for a stretch, winning every aerial duel and delivering a decisive header.",
      chargeRequired: 55,
      effect: { type: "stat_boost", stat: "physical", magnitude: 50, durationTicks: 6 },
    },
    portrait: "hawk",
    flavorText: "The pitch is a chessboard. Hawk already knows your next three moves.",
  },
];
